# Generated by Django 4.0.2 on 2022-11-08 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(max_length=2000)),
                ('language', models.TextField(default='text', max_length=20)),
                ('public', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('password', models.TextField(default='QnADt3s536qV9Dp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
