# Generated by Django 4.0.2 on 2022-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='password',
        ),
        migrations.AddField(
            model_name='notes',
            name='access',
            field=models.TextField(default='eRetNGFzuLj8pLj'),
        ),
    ]
