# Generated by Django 4.0.2 on 2022-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notes_access_notes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='password',
            field=models.TextField(default='JC4Fcn5sQmk2hkK'),
        ),
    ]
