# Generated by Django 4.0.2 on 2023-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='password',
            field=models.TextField(default='bHxabdTZMHGVmqL'),
        ),
    ]
