# Generated by Django 4.1.3 on 2023-09-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_notes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='password',
            field=models.TextField(default='MQsA7TGTkt3ahY9'),
        ),
    ]
